[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
  to = "https://ruverse.netlify.app/:splat"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, PUT, POST, DELETE, OPTIONS, FETCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Content-length, X-Requested-With, Accept"