[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  from = "/*"
  to = "https://ruverse.netlify.app/:splat"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"