
[[redirects]]
  from = "/proxy/*"
  to = "https://ruverse.snu.ac.kr/:splat"
  status = 200
  force = true
  # Logging level for Netlify
  headers = { "X-Logging": "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
