[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/video/*"
  to = "https://ruverse.snu.ac.kr/video/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}